User's Guide
------------

This part of the documentation will show you how to get started in using
PyTransmit.

.. toctree::
   :maxdepth: 2

   quickstart

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

See PyTransmit license_ for legal information governing this project.

.. toctree::
   :maxdepth: 2

   changelog

.. _license: https://github.com/ajkumar25/PyTransmit/LICENCE.txt
